apiVersion: v1
kind: Service
metadata:
  name: brave-mcp
  labels:
    app.kubernetes.io/name: brave-mcp
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: brave-search
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: brave-mcp
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP